### ISSUE TITLE
初めまして。AEIOUのことでお願いごとがあります。

### ISSUE THREAD

**Issue by tailsred** [pikovolt/AEIOU#1]
初めまして。
私はタカヨシと申します。
いつもお世話になっております。
AEIOUのことでご相談があります。
AEが2024にバージョンアップしながら今まで使っていたAEIOUのリマップが使えなくなりました。
（コピーペーができなくなる）
今使っているものがAEIOUｖ1.11ですがキーフレームのデータが4.0なのが原因で9.0に変える必要があるそうです。
もしかしてAEIOUｖ1.11のマスターデータをいただけないでしょうか？
大変失礼なお願いだとは思いますが長年使っていたもので一番慣れたものなのでこれがないと本当に困ります。。
どうかご理解していただけると助かります。。
何卒ご検討宜しくお願い致します。

**Comment by pikovolt** [comment]
申し訳ないのですが、古いバージョンのソースコードがいま手元にありません。
また、そのバージョンのビルド環境も VisualStudioではない頃のものなので、ソースコードがあったとしても、いまから環境を手に入れるのも難しいのではないかと思われます。

誠に申し訳ないのですが、新しいものをご利用戴くか、別のソフトをご検討戴くようにお願い申し上げます。
ご迷惑をお掛けして、本当に申し訳ありません。

**Comment by tailsred** [comment]
ご返答ありがとうございます！
こちらこそ大変失礼なお願いをしまして申し訳ございませんでした。。
AEIOUは直感的で本当に使いやすいです！
現在ｖ3.0.0.3のデータは残っているようですがもう新しい開発はされないでしょうか？
もしこれ以上更新がなければ自分の方でデータ改良などを行っても大丈夫なものでしょうか、、？
ご迷惑をおかけしまして申し訳ございません。
何卒ご検討宜しくお願い致します。

**Comment by pikovolt** [comment]
ここに公開している物を独自に改修して戴くのは自由なので、forkして改修版を公開して戴ければと思います。
ここで公開中のものは、基本的に新しい機能追加などの予定はありません。
修正することもあるかもしれませんが、バグ修正やAfterEffects側の仕様変更への対応くらいになると思います。

以上、よろしくお願いいたします。

**Comment by tailsred** [comment]
ご返答ありがとうございます！
かしこまりました。一度挑戦してみます。
ありがとうございます。大変お世話になりました。

**Comment by pikovolt** [comment]
すみません、補足です。
v3の場合、「AEへコピー」機能は２種類あるのですが、スクリプト仲介の方を使えば、AEIOU->AEへのペーストはできているようです。

**Comment by tailsred** [comment]
ご親切にありがとうございます！
STSなども使ってみましたがなかなか手につかなくて、、やはりAEIOUに戻っちゃいます。
スクリプトの方も試してみます。
ありがとうございます。
